### ISSUE TITLE
Hooks Customization

### ISSUE THREAD

**Issue by Yodzorah** [justdanpo/VivaldiHooks#22]
Hello.

I think, there is some need of good directories' structure:

> * Hook Mod/
> * * img/
> * * hooks/
> * * * css/
> * * * js/
> * * * img/

... and the mod manual. I'm trying to import my own hook into your "hook manager", and it could be far simplier with some logic structure and a detailed manual.

Thank you for your nice job, nevertheless. It's really cool.

**Comment by justdanpo** [comment]
I don't know why I haven't answered here. You may use any folder structure for your mods' resources except js/css. I had been using Opera12 skin for a while which kept images in `hooks/o12/`. Css itself contained links like this:

```css
button.button-addressfield.addressfield-siteinfo:before {
  background-image: url("/hooks/O12/page-web.png") !important;
}
```
